language: node_js
node_js:
  - node
  - 6.11.0
services:
  - postgresql
cache:
directories:
 - node_modules
script:
  - npm install
  - npm run server:test
after_success:
  - npm run coveralls
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info
env:
  - NODE_ENV=test

