language: node_js

node_js: "7"

install:
- npm install

script:
- npm test

env:
- NODE_ENV=test

cache:
  directories:
  - "node_modules"

services:
- postgresql

before_script:
- createuser postgres -s -U postgres
- createdb moreRecipesTest --username=postgres
- sequelize db:migrate

notifications:
  webhooks: https://coveralls.io/webhook repo_token=7yowXLWuuvTUGR5B6WH2KPfRQES3rHVuz

after_success: npm run coverage