language: node_js
node_js: "7"
install:
- npm install
script:
- npm test
env:
- NODE_ENV=test
cache:
 directories:
  - "node_modules"
services:
 - postgresql
before_script:
- npm install nyc -g
- npm install mocha -g
- createdb more_recipes_test --username=postgres
notifications:
 webhooks: https://coveralls.io/webhook
