language: node_js

node_js:
  - node
  - 6.11.0

services:
  - postgresql
  
script:
  - npm run test
  
before_script:
  - psql -c 'create database more_recipes_test;' -U postgres
  - npm install sequelize -g
  - npm run migrate

