language: node_js

node_js:
  - node
  - 6.11.0

services:
  - postgresql
script:
  - npm run test
  
before_script:
  - psql -c 'create database more_recipes;' -U postgres
  - npm install sequelize -g
  - npm run migrate

after_script:
  - psql -c 'drop database more_recipes;' -U postgres

addons:
  postgresql: "9.4"